<?php
/*
 * Care by Zinc in Product Page
 */
?>
<?php
$product_id = Mage::registry('current_product')->getId();
$product = Mage::getModel('catalog/product')->load($product_id);
$productType = $product->getTypeId();
$price = $product->getFinalPrice();
$helper = Mage::helper('carebyzinc');

$session = Mage::getSingleton("core/session",  array("name"=>"frontend"));
$interstitials = $session->getData('interstitials');
$iVisability = $helper->checkInterstitalVisibility();

if (($productType == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE || $productType == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) && ($product->getCarebyzinc() == 1) && ($helper->checkQuoteVisibility('product'))):
    $zip = $helper->getZipCode();
?>
    <div class="product-box">
        <input type="text" name="zipcode" id="zipcode" value="<?php echo $zip; ?>" placeholder="Enter Zip code here" style="width:21%"/>
        <button class="btn-zinc showCarebyzinc">Get Quote <span id="care-loader" class="care-loader"></span></button>  
        <div id="carebyzincCnt"></div>
        <input type="hidden" name="isProduct" value="1" />
    </div>
<?php if($iVisability) : ?>
<?php if($interstitials && isset($interstitials['html'])) : ?>
    <div id="interstitials" style="display: none;">
        <link rel="stylesheet" type="text/css" href="<?php echo $interstitials['stylesheet']; ?>" />
        <?php echo $interstitials['html']; ?>
    </div>
<?php endif; ?>
<?php endif; ?>
    <script>
        //<![CDATA[
        jQuery(document).ready(function () {
            showCarebyzinc();
        });

        function showCarebyzinc() {
            var val = document.getElementsByClassName("super-attribute-select");
            var customoption = document.getElementsByClassName("product-custom-option");
            var i;
            var configOptions = '';
            if (val.length)
                configOptions = '{';
            for (i = 0; i < val.length; i++) {
                var option = (val[i].name).match(/\d+/)[0];
                configOptions = configOptions + '"' + option + '":' + val[i].value;
                if (i != (val.length - 1))
                    configOptions = configOptions + ',';
            }
            if (val.length)
                configOptions = configOptions + '}';
            var customoptionPrice = 0;
            for (i = 0; i < customoption.length; i++) {
                var option = customoption[i].value;
                var selectedIndex = customoption[i].selectedIndex;
                if (selectedIndex)
                    customoptionPrice = customoptionPrice + customoption[i][selectedIndex].getAttribute('price');
            }
            var zip = document.getElementById('zipcode').value;
            if (zip) {

                if (/(^[A-z0-9]{2,10}([\s]{0,1}|[\-]{0,1})[A-z0-9]{2,10}$)/.test(zip)) {
                    var url = '<?php echo $this->getUrl("carebyzinc/index/pricequote") ?>';
                    jQuery("button").addClass("selected");
                    jQuery("#care-loader").addClass('show');
                    new Ajax.Request(url, {
                        method: 'post',
                        parameters: {pid: <?php echo Mage::registry('current_product')->getId(); ?>, zip: zip, configOptions: configOptions, customoptionPrice: customoptionPrice},
                        onComplete: function (transport) {
                            var content = JSON.parse(transport.responseText);
                            jQuery("#carebyzincCnt").show();
                            $('carebyzincCnt').update(content);
                            jQuery("#care-loader").removeClass('show');
                            jQuery("button").removeClass("selected");

                        }

                    });
                }
                else
                    alert('Enter a valid zip code');
            } else
                alert('Enter a valid zipcode');
        }
        jQuery(".configurable-swatch-list li a").click(function () {
            jQuery("#carebyzincCnt").hide();
            $('carebyzincCnt').update('');
        });
        jQuery("select.super-attribute-select").change(function () {
            jQuery("#carebyzincCnt").hide();
            $('carebyzincCnt').update('');
        });

        function checkAction(item) {
            var radioButtons = $("input[type='radio'][name='" + item.name + "']");
            var radioStates = {};
            jQuery('input[name=' + item.name + ']').click(function () {
                var val = jQuery(this).val();
                jQuery(this).attr('checked', (radioStates[val] = !radioStates[val]));

                jQuery.each(radioButtons, function (index, rd) {
                    if (rd.value !== val) {
                        radioStates[rd.value] = false;
                    }
                });
            });
        }

        //]]>	 
    </script>

<?php if($iVisability) : ?>
<?php if($interstitials && isset($interstitials['html'])) : ?>
    <script>
        //<![CDATA[
        jQuery(document).ready(function() {
            jQuery.colorbox({
                inline: true,
                href: "#interstitials",
                width: 728,
                fastIframe: false, 
                innerHeight: 325,
                open: true,
                escKey: false,
                overlayClose: false,
                onLoad: function() {
                    jQuery('#cboxClose').remove();
                },
                onClosed: function() {
                    jQuery('#interstitials').hide();
                },
                onOpen: function() {
                    jQuery('#interstitials').show();
                }
            });
            
            jQuery('.ZincInterstitial-productInfoPrice').html('<?php echo $interstitials['real_price']; ?>');
            jQuery('input#qty').attr('value', '<?php echo $interstitials['qty'] ?>');
            qty
        });
        
        jQuery('#ZincInterstitial-cancel').click(function() {
            jQuery.colorbox.close();
            var url = '<?php echo $this->getUrl("checkout/cart/ajaxprocessitem") ?>';
            new Ajax.Request(url, {
                method: 'post',
                parameters: {pId: <?php echo Mage::registry('current_product')->getId(); ?>, action: 'cancel', qty: <?php echo $interstitials['qty']; ?>},
                onComplete: function (transport) {
                    var content = JSON.parse(transport.responseText);
                    if(content != false) {
                        window.location.replace(content);
                    }
                }
            });
        });
        
        jQuery('#ZincInterstitial-add').click(function() {
            jQuery.colorbox.close();
            var url = '<?php echo $this->getUrl("checkout/cart/ajaxprocessitem") ?>';
            jQuery('#carebyzincCnt input[name="carebyzinc_option"]').attr('checked', 'checked');
            new Ajax.Request(url, {
                method: 'post',
                parameters: {pId: <?php echo Mage::registry('current_product')->getId(); ?>, action: 'add'},
                onComplete: function () {
                    jQuery('.add-to-cart-buttons .btn-cart').trigger('click');
                }
            });
       });
        //]]> 
    </script>
<?php endif; ?>
<?php endif; ?>
<?php endif; ?>