<?php $quoteData = $this->getQuoteData(); ?>
<?php if(!empty($quoteData)): ?>
    <?php if( is_array($quoteData) && $quoteData['code'] == '200') : ?>
        <div class="product-wrap">

        <ul class="product-list">
          <?php foreach($quoteData['price'] as $item): ?>
              <li>
                  <div class="bx-l">
                      <div class="squared input">
                          <input type="radio" value="<?php echo $item['id']; ?>" id="carebyzinc_<?php echo $item['id']; ?>" name="carebyzinc_option" onclick="checkAction(this)"/>
                          <label for="carebyzinc_<?php echo $item['id']; ?>"></label>
                      </div>
                  </div>
                  <div class="bx-r">
                      <h2 class="p-price"><?php echo Mage::helper('core')->currency($item['price_per_year']); ?></h2>
                      <h3 class="p-name quotelabel"><?php echo $item['description']; ?></h3>
                  </div>
              </li>
          <?php endforeach; ?>
        </ul>
        </div>
        <script>
        //<![CDATA[
         jQuery(".quotelabel").on("click","a", function(event){
                event.preventDefault();
                var elementURL = jQuery(this).attr("href");
                jQuery.colorbox({iframe: true, href: elementURL, innerWidth: 645,fastIframe: false, innerHeight: 509,width:"70%"});
              });
          //]]> 
        </script>
    <?php elseif ($quoteData['code'] == '400') : ?>
        <div id="warning_div">
            <p class="error-msg"><?php echo $quoteData['title']; ?></p>
            <p class="error-details"><?php echo $quoteData['details']; ?></p>
        </div>
    <?php endif; ?>
<?php else : ?>
    <p class="error-msg"><?php echo $this->__( 'No quotes available');?></p>
<?php endif; ?>
